server:
  port: 8080


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?directConnection=true
      database: bankAccount

  kafka:
    producer:
      bootstrap-servers:
        - localhost:39092
        - localhost:39093
        - localhost:39094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer